name: Keep Render Backend Alive

on:
  schedule:
    - cron: "*/2 * * * *"  # Every 5 minutes
  workflow_dispatch:       # Allows manual trigger

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Render Backend
        run: curl -s https://expense-backend-lejp.onrender.com/ping || echo "Ping failed"
